name:                electra2shadow
version:             0.1.0.0
github:              "guillaumecherel/electra2shadow"
license:             BSD3
author:              "Guillaume Chérel"
maintainer:          "guillaume.cherel@iscpif.fr"
copyright:           "2018 Guillaume Chérel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/guillaumecherel/electra2shadow#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  electra2shadow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - electra2shadow

tests:
  electra2shadow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - electra2shadow
